create_clock -period 40.00 -name i_Clk [get_ports i_Clk]

set_property IOSTANDARD LVCMOS33 [get_ports i_Clk]
set_property IOSTANDARD LVCMOS33 [get_ports o_LED_1]
set_property IOSTANDARD LVCMOS33 [get_ports o_LED_2]
set_property IOSTANDARD LVCMOS33 [get_ports o_LED_3]
set_property IOSTANDARD LVCMOS33 [get_ports o_LED_4]
set_property IOSTANDARD LVCMOS33 [get_ports o_LED_5]
set_property PACKAGE_PIN W5 [get_ports i_Clk]
set_property PACKAGE_PIN U16 [get_ports o_LED_1]
set_property PACKAGE_PIN E19 [get_ports o_LED_2]
set_property PACKAGE_PIN U19 [get_ports o_LED_3]
set_property PACKAGE_PIN V19 [get_ports o_LED_4]
set_property PACKAGE_PIN W18 [get_ports o_LED_5]
